### ISSUE TITLE
Adding condition on /proc/sys/kernel/deny_new_usb in systemd service

### ISSUE THREAD

**Issue by dvzrv** [anthraxx/usbctl#6]
On kernels, that don't have `/proc/sys/kernel/deny_new_usb` (e.g. default Arch Linux kernel), it would be great, if the `deny-new-usb.service` would not fail, but rather just not work.

This can be achieved by using

```
ConditionFileNotEmpty=/proc/sys/kernel/deny_new_usb
```

in the `[Unit]` section of the service.

**Comment by dvzrv** [comment]
Urgh... I think this was probably bad advice!
It fails to start on linux-hardened, although the file is there and not empty (contains `0` when not active). It's size is zero though, which is why... :-/

Using `ConditionPathExists=/proc/sys/kernel/deny_new_usb` works on linux-hardened though and fails on linux (as intended).

Sorry, but I think I made a bad assumption there.

**Comment by anthraxx** [comment]
Indeed, but i should have better tested this as well >.>
thanks anyway
