### ISSUE TITLE
Feature Request: Allow whitelisting by USB device ID

### ISSUE THREAD

**Issue by hardfalcon** [anthraxx/usbctl#9]
It would be cool if there was a possibility to whitelist devices based upon their USB ID.

For example, M.2 cellular modems are usually USB devices and get switched off when the laptop lid gets closed or the laptop goes into standby. Upon resuming from standby, they get powered on again, thus appearing as a "newly plugged-in device" to the kernel and hence being blocked when deny_new_usb is supported and usbctl is active.

The workaround for this is to temporarily disable deny_new_usb, close the laptop lid again, wait a few seconds, then resume from standby, and reenable deny_new_usb once the cellular modem is working again. This is obviously rather time-consuming and annoying, hence this feature request.

**Comment by anthraxx** [comment]
This is not possible in usbctl as its just a userspace helper to enable/disable usb in kernel space. The deny_new_usb kernel feature itself is additionally created to be a simple bullet proof switch to not do anything with usb subsystem in kernel or userspace and eliminate any kind of attack surface or bypass.

The rule part that you wish already exists in the kernel, it has a policy/rule enforcement facility that reads usb information and passes it to userspace before potentially continuing (including device id and driver whitelisting). One userspace implementation for that is 'usbguard'  which can f.e. be found in the Arch repository.

The idea of deny_new_usb is to not process anything and just deny in an as early stage in the kernel as possible including not passing or interacting with userspace as well. It pretty much depends on your paranoia level, but speaking for myself I use both at the same time, so basically I use the temporary command of usbctl whenever i want to add a new usb device and then allow it further via device ids in usbguard :cat: The way i do it (using both) of cause will not solve your issue with resume/standby but that really depends on your choice and paranoia level.

**Comment by hardfalcon** [comment]
Thanks for the hint. Btw, it seems there is an [additional kernel-side feature coming with kernel 5.1](
https://git.kernel.org/pub/scm/linux/kernel/git/gregkh/usb.git/commit/?h=usb-next&id=7bae0432a64aa7569dbd0feb2927fd3ff913901f) which might allow usbguard to distinguish between internal and external USB ports.
